### ISSUE TITLE
Measure tests coverage?

### ISSUE THREAD

**Issue by webknjaz** [python-attrs/attrs#1014]
@nedbat says that [it's important to do this][1], and I agree. Any specific reason, it's not done? I noticed that back when [Codecov was still in use][2], the tests coverage wasn't being uploaded either, so it's probably not related to migrating off of it.

This ocurred to me when I was looking at the coveragepy config and only saw `attr`/`attrs` in `source_pkg` but not `tests`. So I started to wonder if there's no `source = tests/`...

[1]: https://nedbatchelder.com/blog/202008/you_should_include_your_tests_in_coverage.html
[2]: https://app.codecov.io/gh/python-attrs/attrs

**Comment by hynek** [comment]
While I would never argue against Ned and while I've indeed found tests that're not run (https://github.com/python-attrs/attrs/commit/649b273c823927650f01150462f7e2c55fe2d13f) because Anthony brought it up to me yesterday too, given the current tests structure I can't go this path. It would mean *a ton* of `# pragma: no cover` statements for all kinds  that aren't meant to run, many of them lambdas, and add an amount of churn that's not worth it.

If we'd be starting from zero, I would totally support that. But the current state is too much work for too little gain.
