### ISSUE TITLE
Why strip leading underscores from attribute names?

### ISSUE THREAD

**Issue by mrolle45** [python-attrs/attrs#1060]
This practice leads to errors in cases like:

```py
class C:
    _1: int          # Already mentioned in your docs.
    x: int
    _x: int          # SyntaxError: duplicate argument 'x' in function definition.
```

Can you explain to me what is the use case for stripping the underscores.  The altered name only appears, as far as I can tell, as a parameter name in the generated __init__ method.
EDIT: `attrs.evolve` is affected, also:
* `evolve(C(1), 
* s
* 

If not, then I consider this a bug and the behavior should be removed.  Or deprecated, at least.

**Comment by hynek** [comment]
This is explained [in the documentation](https://www.attrs.org/en/stable/init.html#private-attributes) & will be improved by #950.

**Comment by mrolle45** [comment]
I see you've been working on this issue already, as in #950.

It looks like I'll see the improvements in a new release of attrs.

**However**, note that I added a **BUG** description to my original comment, and I'd like you to see that it gets fixed.

Thank you.

**Comment by asford** [comment]
> I see you've been working on this issue already, as in #950.
> 
> It looks like I'll see the improvements in a new release of attrs.
> 
> **However**, note that I added a **BUG** description to my original comment, and I'd like you to see that it gets fixed.
> 
> Thank you.
> 

@mrolle45 

I'd like to use this thread, though the issue is already closed, to provide some constructive feedback on why there are a few thumbs down on your comment.

In a project of this type we are all working together to implement an open source library. In this effort we all have important roles. Hynek is operating as maintainer and primary author, but there are other contributors. Here, you're actually playing a very important role as an issue contributor. 

One of our roles as issue contributors, or even as contributing authors to attrs, is to make very very efficient use of Hynek's time. Writing effective and clear issue descriptions, with repro cases of the type you've provided is extremely useful. Thanks!

However, it's also very important to look through the context in the project to crosslink your issues, determine if work is already in progress or if the behavior is known. In this issue and the other that you opened, you didn't do this effectively because you didn't evaluate or demonstrate if the referenced PR would address your repro and didn't carry those references forward into the issue.

The best way to see issues fixed in a project is to provide very solid context, ideally even at the level of a test case for the issue that you are seeing. The tone ending your last comment (" I'd like you to see that it gets fixed") was not effective in ensuring your issue will be addressed. As issue reporters, our time is actually *less precious* than the core maintainer's. 

Even from a strictly self-interested perspective, where you only care about having the issue resolved, it would be far more effective to read the context carefully and ask "what can I do help ensure this is fixed?".
