### ISSUE TITLE
Validation before conversion

### ISSUE THREAD

**Issue by klausmcm** [python-attrs/attrs#1086]
I understand that conversion occurs before validation

> Converters are run before validators, so you can use validators to check the final form of the value.

https://www.attrs.org/en/22.2.0/init.html#converters

Is there a way to change that behavior? I have not found anything in the documentation that would allow me to change the order. **I would like to do validation before conversion**.

One limitation with "abusing converters as one-argument validators" is that I cannot get the attribute name that failed the validation.

Should I be doing the conversion in `__attrs_post_init__` instead?

Thanks

**Comment by hynek** [comment]
Yeah there is no way.

We've had thoughts about unifying those two concepts better (there's open issues about it somewhere) to give our users more flexibility, but since we never found a way that made everybody happy, it never progressed.

When I need more control over initialization like this, I tend to use the **post** init hook.

**Comment by klausmcm** [comment]
post init it is then. Thank you for confirming!
