### ISSUE TITLE
TypeError: with a diamond-like multiple inheritance

### ISSUE THREAD

**Issue by roynico** [python-attrs/attrs#1116]
Hello, 

I encounter a problem when trying to use attrs class with a diamond-like inheritance:
The error : 
```
...  class D(B, C):
TypeError: multiple bases have instance lay-out conflict
```

Minimal Example: 

```
from attrs import define, field

@define
class A:
    a: str = field()

@define
class B(A):
    b: str = field()

@define
class C(A):
    c: str = field()

@define
class D(B, C):
    d: str = field()


```

I do not understand why there should be any conflict in this example.

**Comment by hynek** [comment]
This is because `@define` uses slots by default and it's [not possible](https://docs.python.org/3/reference/datamodel.html#notes-on-using-slots) to inherit from more than one slotted class.

See also our glossary: https://www.attrs.org/en/stable/glossary.html#term-slotted-classes

Usually that's not a problem, because diamond-like inheritance is generally considered bad design. If you want to force it, pass `(slots=False)` to the last define.

**Comment by roynico** [comment]
Many thanks for the quick answer !
