### ISSUE TITLE
Using `attr` library instead of `attrs` in documentation

### ISSUE THREAD

**Issue by Why-not-now** [python-attrs/attrs#1162]
In the documentation, there is a mix of usage of the libraries `attr` and `attrs`. One example of this is in [here](https://www.attrs.org/en/stable/examples.html#immutability), where the docs referenced `attr.evolve` and used `attrs.evolve` in the example code. This confused me on the first read through of the documentation. Is updating the documentation to be using the library `attrs` in the works?

**Comment by hynek** [comment]
Generally speaking we try to use `attrs.` wherever possible. You actually found bug in the docs, because that `attr.evolve` used to be a link to the reference but somehow didn't make it through conversion so thanks for that! The rule is kinda that if only one syntax is used, use `attrs.`. But there's a lot of docs…

**Comment by Why-not-now** [comment]
So is there work being made for the `attr` module to be replaced by `attrs` module in the docs? Also glad to help out and all the best to you guys.

**Comment by Tinche** [comment]
Shoot us a PR and we'll gladly merge it in 🙏

**Comment by Why-not-now** [comment]
> Shoot us a PR and we'll gladly merge it in 🙏

There is one paragraph I still do not have a good understanding on:
> You can still have power over the attributes if you pass a dictionary of name: [field()](https://www.attrs.org/en/latest/api.html#attrs.field) mappings and can pass arguments to @attr.s:
