### ISSUE TITLE
Multiple inheritance produces a TypeError (though dataclasses work fine)

### ISSUE THREAD

**Issue by brettc** [python-attrs/attrs#1261]
attrs version: 23.2.0
Python version: 3.11.8
Operating System: OSX

Yeah, multiple inheritance is evil. But I have situation where it makes sense. Interestingly, it works fine for dataclasses, but fails with attrs.

```
from attrs import define
from dataclasses import dataclass


@dataclass(kw_only=True)
class Ad:
    a: str = ""


@dataclass(kw_only=True)
class Bd:
    b: str = ""


# This is totally fine
@dataclass(kw_only=True)
class Cd(Ad, Bd):
    c: int = 3


@define(kw_only=True)
class Aa:
    a: str = ""


@define(kw_only=True)
class Ba:
    b: str = ""


# Gives TypeError: multiple bases have instance lay-out conflict
@define(kw_only=True)
class Ca(Aa, Ba):
    c: int = 3
``

**Comment by hynek** [comment]
This is an issue of multiple inheritance together with slotted classes. See the third item in https://www.attrs.org/en/stable/glossary.html#term-slotted-classes (or search for your error message).

You can fix it by disabling slots for some of the classes. It works with data classes because there slots are opt-in while in *attrs* they're opt-out.

**Comment by brettc** [comment]
My apologies for the noise -- and thanks for the explanation. I've used the previous API to attrs for a long time, and was unaware that `define` gave me slots.
