### ISSUE TITLE
Crash when annotating type with the python syntax (a: T = attrib())

### ISSUE THREAD

**Issue by userappgate** [python-attrs/attrs#1282]
```python3

from attr import attrs, attrib
import staffetta.settings

@attrs(frozen=True)
class A:
    staffetta = attrib(type=staffetta.settings.Settings)

@attrs(frozen=True)
class B:
    staffetta: staffetta.settings.Settings = attrib()
```

That code results in

```
Traceback (most recent call last):
  File "/build/project/qwe.py", line 9, in <module>
    class B:
  File "/build/project/qwe.py", line 10, in B
    staffetta: staffetta.settings.Settings = attrib()
AttributeError: '_CountingAttr' object has no attribute 'settings'
```

It was my understanding that the two syntax were equivalent, but it seems they are not. The 1st one works but the second does not.

The imported class is this

```python
# cat /usr/lib/python3/dist-packages/staffetta/settings.py
from typing import NamedTuple

class Settings(NamedTuple):
    log_level: int
```

The __init__ of that module is just an empty file.

**Comment by euresti** [comment]
This is really quirky.  It's not an attrs specific issue since you can trigger it like this:

```
import pathlib

class A:
      pathlib: pathlib.Path = 'foo'
```

It happens because the pathlib inside the type annotation is interpreted in the context of the class, and because of the equal sign it says "`pathlib` is `'foo'` so what's `'foo'.Path`.  

The solution is to use a different name:

```
@attrs(frozen=True)
class B:
    settings: staffetta.settings.Settings = attrib()
```

or to change your import:
```
from staffetta.settings import Settings
```

Basically avoid things having the same name and the problem goes away.

**Comment by userappgate** [comment]
Aaaah! I thought there was something with the class triggering it.

I guess it's a mypy error that it says it's ok then though.
