### ISSUE TITLE
[RFC] Add attrs package

### ISSUE THREAD

**Issue by hynek** [python-attrs/attrs#131]
So many people like the serious biz names which is sad but unfixable.  I am sometime irked when doing something like `from attr.validators import whatever` myself.  Other people are confused by the fact, that the package name is `attrs` but you import from `attr` (there’s #123 but many more people complained on Twitter/IRC/…).

It has been quite a while on my mind to solve all of the above by adding another module called `attrs` that is basically just a `from attr import *  # noqa`.

## Upsides

1. serious biz people have nicer imports for `attrs` and `attr`
2. everyone has nicer imports for everything else.

## Downsides

1. `There should be one-- and preferably only one --obvious way to do it.`  Although we violate it anyways.

Comments? Opinions?  @glyph @Tinche @exarkun @cournape @ncoghlan @guettli

(Anyone can and *should* voice their opinion.   But this is *not* a vote.  I’ll decide based on the arguments made.  If you just wanna vote anyway, please use reactions and don’t spam with “+1”s – thanks :))

**Comment by p-himik** [comment]
A minor point on having `attrs` - Pycharm always complains that I don't have `attr` installed. I have no idea if they installed packages simply by name, but I hope the warning will go away once I start using `attrs`.

**Comment by mjtamlyn** [comment]
Whilst I appreciate why people like the explicit `attrs.attribute` style syntax, I personally find `attr.ib` and `attr.s` to be extremely elegant, and it's one of the things which persuaded me to use the module at all.

You're going to be forced to have a trade off somewhere here. Either you lose one of the syntaxes (short or longhand), or you have multiple ways to do it. If we're accepting the trade off that there are multiple ways to do it to keep both camps happy, then we may as well do it everywhere, including the `attrs`/`attr` import. 

There's an option for a completely separate build, but that sounds worse ;)

**Comment by grantmcconnaughey** [comment]
Another issue to consider is that `attrs.ib` and `attrs.s` won't make a ton of sense.

**Comment by hynek** [comment]
To be clear: `@attr.s` and `@attr.ib` aren’t going anywhere.  The elegance will stay.  `s` and `ib` won’t go into `attrs` though.

**Comment by Insoleet** [comment]
Why not rename the project `attr` ?

@p-himik : pycharm does not complain here. You muse have some problem in your environment.

**Comment by pauricthelodger** [comment]
In the documentation, are you planning to tell users to `from attr import foo` or `from attrs import foo`?

**Comment by hynek** [comment]
That’s a good question.  And I’ll decide on that once I’ve seen a few examples.  Since you usually import `attr` and possibly the tools separately, it should be a problem in general. OTOH

```python
import attr
import attrs

@attr.s
class C:
    x = attr.ib()

attrs.asdict(C(1))
```

obviously is rather gross.

***

It’s also possible that the docs will start using srs biz syntax at some point because I’m *so sick* of people publicly bashing attrs because of it.  But again, nothing is gonna be deprecated or removed.

**Comment by p-himik** [comment]
Examples that I don't find that gross:
```python
from attrs import attr

@attr.s
class A:
    a = attr.ib()
```
or
```python
from attrs import attrs, attrib

@attrs
class A:
    a = attrib()
```
The second example of course does not imply that `attr.ib` and `attr.s` should be removed. But maybe they should be deprecated.

**Comment by hynek** [comment]
- They won’t be deprecate as long as I breathe but as I wrote in my last paragraph: serious business might become the default in docs.
- Your first example is a nice workaround!

**Comment by justinmayer** [comment]
What do all the mentions of "serious biz/business" in this issue refer to? I can't help but feel like I am missing something.

**Comment by exarkun** [comment]
Early on, I believe I voiced my strong opinion against the cute names which are present in `attrs` at the time of this discussion.  I still hold those opinions.  I think an alternate API _would have been_ better for the project and its users.

However, at this point, I think you (hynek) should stick with your decision.  I would not see the *addition* of new, equivalent APIs alongside the existing ones as an improvement.  It will make reading attrs-using code harder by forcing everyone to learn both spellings.  It will be another essentially irrelevant decision to make for each user of the library.  I think that you will prove the best version of attrs possible by imposing your coherent vision on the project.  I'm glad you're not making this a vote but I want to emphasize that as the author and maintainer you should be sure to give your own opinion sufficient weight (ie, the most) in coming to a conclusion on this point.

**Comment by Tinche** [comment]
I used to be mildly irked by the attr/attrs inconsistency, but I'm over it (and cattrs currently uses the cattr package, modeled after attrs).

I don't have a strong opinion one way or the other since they all have drawbacks, and that means the status quo wins for me.

**Comment by glyph** [comment]
I think there are two separate questions here.

One is, should we add a top-level `attrs` package?

The other is, is srs bsns the way to go for names in general?

To the first, I'd say: strong maybe.  The motivation for adding a top-level `attrs` package is _discoverability_.  Some people hear about `attrs`, `pip install attrs`, and then `import attrs` to snoop around with Jupyter or bpython or something, and are surprised when `import attrs` doesn't work.  If they'd started with the docs they'd know what to do, but not everybody rolls that way.

Since we're voting, I suppose I'd say I'm +0 on this.  It makes sense to me to do it, but it doesn't make sense to me to document it; just put the alias there, and maybe emit a warning or something when it's imported, to say "uh, I think you mean `attr`" so that users get a better experience with the out-of-the-box noodling-around introduction rather than the "let's read the docs" introduction.

To the second, I'd echo @exarkun's comments, except of course I thought the cutesy names were brilliant from the start.  If anything, I'm a little sad about the existence of the srs bsns aliases in the library itself, I would have just put `from attr import s as following_class_contains_attributes, ib as declarative_attribute_declaration` in the documentation somewhere and be done with it.

**Comment by glyph** [comment]
@justinmayer 

> What do all the mentions of "serious biz/business" in this issue refer to? I can't help but feel like I am missing something.

search for "serious business" on https://attrs.readthedocs.io/en/stable/api.html.

They refer to the `attr.attrs` and `attr.attrib` aliases for `attr.s` and `attr.ib`.

**Comment by justinmayer** [comment]
Thanks, @glyph. This topic makes much more sense to me now.

**Comment by ncoghlan** [comment]
Similar to @glyph, I'm +1 on the top level "attrs" alias for the sake of discoverability.

Where I differ is that I think it would make sense to explicitly separate out the two ways of using it as the "concise style":

    import attr
    @attr.s
    class Concise:
        field = attr.ib()

And the "verbose style":

    from attrs import attributes, attrib

    @attributes
    class Verbose:
        field = attrib()

I'm biased on that front though, as I strongly prefer the more verbose aliases for my own use, and it doesn't have anything to do with find the shorthand versions overly cute.

Instead, it's an artifact of how I've learned to read Python code: my brain often *filters out* the namespace info that appears before the final dot in an attribute reference, and that makes the "attr.s" and "attr.ib" shorthands nigh-unreadable for me (when the "attr" gets mentally filtered out, I'm left with a nonsensical "s" and "ib"). Clearly not everyone does that, but for those of us that do, parsing "attr.s" and "attr.ib" in code is akin to trying to read a sentence that has addition al ran dom spac es in som e of the word s.

**Comment by Tinche** [comment]
I'm really liking @glyph's idea of a shadow attrs module, with a warning printed on import. He has also convinced me the serious business aliases were probably a mistake since Python already has language level features to deal with this very situation.

@hynek you mentioned there already was an attr module on PyPI, are we trampling over someone's package name by using attr ourselves? :D

**Comment by Tinche** [comment]
If someone has the willpower and the time, [here's](https://libraries.io/pypi/attrs/usage) a list of (currently) 237 projects depending on attrs. The percentage of those using the serious vs cute aliases would be an interesting data point, perhaps.

**Comment by IlyaSkriblovsky** [comment]
@Tinche, such statistics would be biased since Serious Business™ stuff might tend to be closed-source.

(I'm using attrs' short syntax in closed-source project at work thought.)

**Comment by ambv** [comment]
Facebook's internal projects that use attrs use the playful syntax. That being said, I like the `from attrs import attr` idea a lot.

**Comment by eliasdorneles** [comment]
I'm not a fan of adding a warning -- if it's a reasonable expectation, why not simply do what the user expects?

And +1 on everything @ncoghlan said. :)

**Comment by hynek** [comment]
A warning is not gonna happen.  There's a very slim chance of breaking someone's imports by adding a new too-level package and I don't want to do it without any tangible gain.

**Comment by kochuyt** [comment]
2cts from a (somewhat) 'serious' business guy:
The naming is what it is, stick with it, don't create confusion by adding 'alternative namings' (especially not in the docs, would only make them less readable for someone like me).

**Comment by alexlouden** [comment]
I came across this project today, pip installed [`attr`](https://pypi.python.org/pypi/attr/) by mistake, and hit the following error, after copying the srs business example: (copied below in full for future discoverability)

```python
from attr import attrs, attrib
ImportError: cannot import name attrs
```

Obviously I've since discovered the problem, uninstalled `attr` and installed `attrs` (bad luck if someone wants to use both!). If the import matched the pypi package (`from attrs import attrs, attrib`) then I don't think I would have made the same mistake. (I'll be using it in a closed source work project)

**Comment by hynek** [comment]
I’m still uncomfortable with importing from `attr` but I’m convinced now, that changing that at this point would do more harm than good.  Thanks to everyone for their input!
