### ISSUE TITLE
Suggestion: differentiate in cmp between (== , !=) and (>,>=, <, <=).

### ISSUE THREAD

**Issue by frip** [python-attrs/attrs#170]
Thanks for a fantastic library!

One thing that surprised me at first was that I could not write an effective `__gt__()`-function for my attr-class. I found the `cmp`-init-parameter later (in the code), but I still wonder if it wouldn't be a good idea if I could have the option of keeping the tuple-based `__eq__` and `__ne__`-implementations, but override size-comparisons (maybe based on a single `__lt__`-function?).

**Comment by Tinche** [comment]
I agree with this suggestion, but for a different reason. I use `cmp=True` for 99% of my classes but only because I want `==` and `!=` to work. Virtually none of these classes I want to be orderable. So there are IMO two good reasons to decouple `__eq__` from ordering.

Not really sure how to deal with backwards compatibility though. Introduce `eq` and `order` (or `ordering`, `ordered`?) arguments to `attr.s`, keeping `cmp` for a year and letting `cmp` override `eq` and `order` if explicitly specified. I would default `cmp` to true and `order` to false.

I'm not sure about the use case where you define `__lt__`. This is already covered by https://docs.python.org/3/library/functools.html#functools.total_ordering, so you can just say:

```
@attr.s(eq=True, order=False)
@total_ordering
class A:
    a = attr.ib()

    def __lt__(self, other):
        ...
```

Or we could actually do this for you if we detect one of the methods.

@hynek @glyph ?

**Comment by glyph** [comment]
This does seem like a good idea.

I think backwards compatibility is reasonably easy; introduce just `eq`, no `order`.  I'd say `cmp=True` means full comparison (i.e.: ordering, since you can't have ordering without equality) and `eq=True` implies `cmp=False`; we can switch `cmp`'s default to be `NOTHING` so as to distinguish "not passed" from "explicit `True`".

**Comment by glyph** [comment]
(Since `cmp` implies `eq`, passing both `eq` and `cmp` explicitly, regardless of their values, ought to be an error, I think.)

**Comment by Tinche** [comment]
I was thinking ideally `cmp` would start defaulting to false, and `eq` to true. This would be a compatibility break, no? In my mind very few classes require ordering. We can be better than namedtuple here :)

**Comment by hynek** [comment]
Four things:

1. I don't care, you'll have to hash it out yourselves. :)
2. We break cmp/hash compat with the next release so this ought to be resolved before 17.1 lands.
3. Do those proposal play well with the current state of cmp at all?
4. We'll I *do* care a bit...are you sure implying a False by passing True to eq is a good, not confusing API? :-/

Also you should consult @njsmith; I'm not merging any changes to those parts without his approval. :)

**Comment by hynek** [comment]
FTR, dataclasses seem to have a split between eq and cmp.

I think it would be nice if an attrs-based back port would be possible and I think currently this is the only feature where attrs is not a superset.

***

It also might be another case where my intention to move from bools to Enums makes a lot of sense.

**Comment by madig** [comment]
I'm interested in this, too. Otherwise, how could this be done elegantly: I have a Status class like this:
```
@attr.s(frozen=True, auto_attribs=True)
class Status:
    weight: int = attr.ib(cmp=True)
    message: str = attr.ib(
        cmp=False,
        converter=lambda value: str() if value is None else value,
    )
    code: str = attr.ib(
        cmp=False,
        converter=lambda value: str() if value is None else value,
    )

    @classmethod
    def Debug(cls, message=None, code=None):
        return cls(weight=0, message=message, code=code)

    [...]

    @classmethod
    def Error(cls, message=None, code=None):
        return cls(weight=6, message=message, code=code)
```
It can be instantiated like this: `Status.Error("This and that is wrong etc.", code="mismatched-something")`. I want to test for equality of two instances using `weight` and `code`, but order only by `weight`.

**Comment by hynek** [comment]
Unrelatedly:

> `converter=lambda value: str() if value is None else value`

I think what you want here is `default=""`?

**Comment by madig** [comment]
I wish, the constructors pass in `None` for stuff and I want to never have a `None` object in there so I don't need to care about `AttributeError`s. I could do this in the constructors but didn't feel like copy-pasting the boilerplate :)

**Comment by hynek** [comment]
Ah…hm…you may get away with using `attr.NOTHING` instead of None in the class methods. :) I don’t know if I should encourage that but it definitely will never stop working.
