### ISSUE TITLE
Extensible asdict ?

### ISSUE THREAD

**Issue by cournape** [python-attrs/attrs#211]
One common attrs usage, at least for me, is to define classes that can easily dumped to/loaded from json. As long as we have "simple types", `asdict` + json.dump/load works well, but it falls down quickly when using recursive structures. E.g.:

``` python
# I would usually use validators, but trying to be brief here

@attributes
class Version(object):
    major = attr()
    minor = attr()

@attributes
class Package(object):
    name = attr()
    version = attr() # type of Version

@attributes
class PackagesSet(object):
    packages = attr() # list of Package instances

packages = PackagesSet([
    Package(u"yolo", Version(1, 2)),
    Package(u"yeah", Version(1, 3)),
])
```

If you do `asdict(packages)`, it will kind of work, but not in a way that is very controllable, because you get `Version` instances "decomposed":

``` python
packages = PackagesSet([
    Package(u"yolo", Version(1, 2)),
    Package(u"yeah", Version(1, 3)),
])

print(asdict(packages))
"""
{'packages': [{'version': {'major': 1, 'minor': 2}, 'name': u'yolo'}, {'version': {'major': 1, 'minor': 3}, 'name': u'yeah'}]}
"""
```

It would be more natural to have something like:

``` python
{"packages": [{"version": "1.2", "name": "yolo"}, "version": "1.3", "name": "yeah"}]}
```

E.g. by using a strawman asdict "protocol":

``` python
@attributes
def Package(object):
    def __attr_asdict__(self):
        return {"name": self.name, "version":  str(self.version)}
    @classmethod
    def __attr_fromdict__(cls, data):
        return cls(data["name"], Version.from_string(data["version"]))
```

Does that make sense ? Or is that something that is considered out of scope ?

**Comment by shwetas1205** [comment]
I am also looking for similar support. I have a class for which I'm supporting two properties which I do not want to support while instantiation of the object because I am making them with the combination of other fields. However, I do want them in asdict/astuple. I am working out for now with defaults and init etc... but __attr_asdict__ kind of override support would just give me the required support I wanted to add. 

Any suggestion on that?

**Comment by Tinche** [comment]
I'm not so hot on the idea of an asdict protocol (we might need `__astuple__` too then). It feels a little too specific.

Instead we should probably focus on `singledispatch` based solutions. @hynek even has a blog post about it: https://hynek.me/articles/serialization/.

I've started an ambitious library to do exactly that: https://github.com/Tinche/cattrs, but due to various obligations I haven't had enough time to really make it first-class yet.

Here's how your use case would look like with cattrs (master branch, not PyPI):

```
from attr import attributes, attr
from cattr import Converter


@attributes
class Version(object):
    major = attr()
    minor = attr()


@attributes
class Package(object):
    name = attr()
    version = attr() # type of Version


@attributes
class PackagesSet(object):
    packages = attr() # list of Package instances


packages = PackagesSet([
    Package(u"yolo", Version(1, 2)),
    Package(u"yeah", Version(1, 3)),
])


c = Converter()
c.register_unstructure_hook(Version, lambda v: "{}.{}".format(v.major, v.minor))

c.unstructure(packages)
# {'packages': [{'name': 'yolo', 'version': '1.2'}, {'name': 'yeah', 'version': '1.3'}]}
```

I plan on picking this up again since it's a common request, maybe put out a new version at the end of the weekend. As I said, I personally think this is the way to go, what do you think?

**Comment by hynek** [comment]
Yeah no protocols, singledispatch ftw.

**Comment by cournape** [comment]
I am not so familiar with `singledispatch`, but not having yet another protocol sounds good to me.
