### ISSUE TITLE
Document how to get support

### ISSUE THREAD

**Issue by The-Compiler** [python-attrs/attrs#247]
Something I'm missing from the docs (e.g. the "project information" block) is what's the best way to ask a question about attrs is. Is there some kind of community somewhere I didn't find, is it okay to open an issue here for questions, or something else entirely? Whatever the answer is, I think it should be documented.

**Comment by hynek** [comment]
Well yeah I'm afraid we have no (official?) answer to that yet. :-/

I've personally had bad experiences with opening an IRC channel because it led to me answering the same questions over and over (#structlog) so I'm rather reluctant to "get another job".

People have organically (ab)used the bug tracker for questions so far so maybe we could just bless it?  At least it wouldn't add another medium, OTOH the burden with helping would land on the maintainers. 

Maybe something with StackOverflow?  That's good for google and linking and somewhat topical.

Don't anyone even dare to bring up Slack. ಠ_ಠ

**Comment by DRMacIver** [comment]
I'd suggest stack overflow. I keep thinking about trying to push the existing Hypothesis tag harder as our official place to ask questions (and am subscribed to the tag  via RSS so I always see questions if they use the right tag).

Our current other answers:

* IRC (fine by me)
* The mailing list (I hate the mailing list and will probably shut it down when I get aroudn to it)
* The issue tracker (it works but I'd kinda rather not)
