### ISSUE TITLE
attrs 17.3 raises AttributeError when using attribs overriding abstract properties

### ISSUE THREAD

**Issue by avish** [python-attrs/attrs#293]
```python
from abc import ABCMeta, abstractproperty

import attr

@attr.s
class Base(object):
    __metaclass__ = ABCMeta
 
    @abstractproperty
    def implement_me(self):
        pass

@attr.s
class Derived(Base):
    implement_me = attr.ib()

Derived("yo")
```

Works in attrs==17.2, breaks with `AttributeError: cannot set attribute` in attrs>=17.3.
Not sure what the correct behavior is, but this is a breaking change for a moderately straightforward use-case (implementing abstract interfaces using fields).

**Comment by hynek** [comment]
This is…interesting and it used to by accident.  First, your code is equivalent to the following:

```pycon
>>> class C(Base):
...     def __init__(self):
...         self.implement_me = 42

>>> C()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in __init__
AttributeError: can't set attribute
can't set attribute
```

So you can’t set an `@abstractproperty` to a value.

It did work before, because `implement_me` got overwritten in the class body which for some reason worked, and then it could just happily assign values.  Now that attrs cleans up behind itself, it’s not masking the property anymore and it explodes.

***

I’m very sorry this broke, but to my understanding, it is the correct behavior.  Now, you’ll have to do something along the lines of:

```python
>>> @attr.s
... class Derived(Base):
...     _implement_me = attr.ib()
...
...     @property
...     def implement_me(self):
...         return self._implement_me

>>> Derived("ypo")
Derived(_implement_me='yo')
```

I’m not sure how feasible/possible it would be to equip attrs with first class property helpers.
