### ISSUE TITLE
First class __weakref__ support

### ISSUE THREAD

**Issue by hynek** [python-attrs/attrs#325]
Currently you get weakref support using a hack that is outlined in #174 that currently doesn’t work properly (#311).

So people like @njsmith rightfully asked for a better solution.  This ticket is to collect all input and decide on an API.

Looking forward to y’all’s input.

**Comment by njsmith** [comment]
My naive suggestion would be to add a new class-level switch `weakref=True`, to control whether classes should be weakrefable. For regular classes this is trivial, so it wouldn't do anything. (Maybe it would be an error to pass `weakref=False`.) For `slots=True` classes, it would control whether attrs auto-added a `__weakref__` slot. By defaulting to `weakref=True`, we made it so that merely toggling between `slots=False` and `slots=True` stops being a breaking change in your public API.

Now I expect there will be some list of reasons involving backcompat why this pretty like suggestion has to be replaced by something more complicated...

**Comment by altendky** [comment]
There wasn't much input but perhaps I can spur some again.  Didn't take too long so not much to lose, don't worry.  :]

**Comment by altendky** [comment]
I suppose I should mention that the reason I ended up looking at this was that I was unable to connect a pyqt signal to a method of a slotted attrs class due to the lack of weakref support.

**Comment by hynek** [comment]
Fixed by #420
