### ISSUE TITLE
cmp=False causes equality to always return True

### ISSUE THREAD

**Issue by iddolev** [python-attrs/attrs#399]
Consider this example:

```
@attr.attrs(slots=True, repr=False)
class Base(object):
    pass

@attr.attrs(repr=False, hash=False, cmp=False, slots=True)
class Derived(Base):
    a = attr.attrib(validator=instance_of(tuple))
    b = attr.attrib(validator=instance_of(dict))

print Derived((1,2), {'a': 1}) == Derived((1,2), {'a': 1})
print Derived((1,2), {'a': 1}) == Derived((1,2), {'a': 2})
```

The printed result is:
True
True
but it should be:
False
False
(assuming that `cmp=False` means: compare by object id).
If we change `cmp=False` to `cmp=True`, we get the correct result:
True
False

**Comment by hynek** [comment]
The problem is that you have no cmp=False in the Base class so it writes one that is True for all Base instances (due to a lack of attributes) and since Derived doesn't overwrite it, it stays that way.

**Comment by avish** [comment]
@hynek, you are correct that this is the expected behavior for a base class that defines an empty comparator. But seeing as `cmp=True` is the default in attrs, it's easy to create base classes with an empty comparator, and then not have an easy way to request reference-equality semantics on subclasses. Perhaps it makes sense to allow some way of explicitly requesting to reference equality semantics, e.g. by allowing `cmp=None` or `cmp=object` to make attrs explicitly call `object.__cmp__` and `object.__eq__`?

**Comment by hynek** [comment]
Well yeah, this goes back to the “abandon bools in favor of enums” plans. The use cases are piling up.
