### ISSUE TITLE
Allow keyword-only attributes before positional attributes

### ISSUE THREAD

**Issue by oakkitten** [python-attrs/attrs#448]
I want to be able to write both `Message("message", timestamp=time.time())` and `Message("message")`, where `timestamp` is an attribute of a base class. Currently the following code:

    @attrs
    class Base:
        timestamp = attrib(kw_only=True, default=None)

    @attrs
    class Message(Base):
        message = attrib()

produces the following error:

    ValueError: Non keyword-only attributes are not allowed after a keyword-only attribute.

As `timestamp` is keyword-*only*, it, as far as I understand, does not pose an ordering issue.

(In my particular use-case, I have a bunch of `Message`s that are convenient to create using positional arguments, but the `timestamp` field is not always meaningful, e.g. for outgoing messages)

**Comment by hynek** [comment]
it’s indeed weird that we don’t allow kw_only attributes anywhere. Someone should research why we chose that route. they are a lot more useful if you can sprinkle them anywhere.

**Comment by wsanchez** [comment]
I suspect that "Non keyword-only attributes are not allowed after a keyword-only attribute" because that's an existing constraint in function argument ordering.

One problem is allowing them anywhere is that the ordering of arguments to `__init__` becomes a bit less obvious, since you need to filter out the `kw_only` attributes.  That's not horrible, but also not nothing.  It could be helped by doc generators that figured that out for you, though.

**Comment by trianta2** [comment]
Agreed this type of functionality would be useful. I'm curious what a current best-practice workaround would look like.

**Comment by hynek** [comment]
This has been fixed by #559
