### ISSUE TITLE
Allow cache_hash=True to be used when a custom __setstate__ is present

### ISSUE THREAD

**Issue by gabbard** [python-attrs/attrs#494]
This is not currently possible (as of the merge of #489 ) because when `cache_hash=True`, we solve #482 by adding a `__setstate__`  to all classes which clears the cached hash code.

This is a somewhat unusual combination of needs, so I imagine this is very low priority. This issue is just here as a marker for anyone who runs into this problem in the future.

**Comment by pganssle** [comment]
How about solving this (albeit mostly theoretical) issue by clearing the hash cache after invoking the custom `__setstate__`, like so (not including changes from #612 for simplicity, and there are lots of variations on how to implement this):

```python
original_setstate = getattr(cls, __setstate__, lambda s, _: None)
def cache_hash_set_state(chss_self, _):
    original_setstate(chss_self, _)
    setattr(chss_self, _hash_cache_field, None)
```

If you consider the hash cache field to be an implementation detail owned by attrs, I think that likely the custom `__setstate__` shouldn't be touching it *anyway*, so this seems pretty safe. If you want a custom `__setstate__` that also has custom behavior involving the hash caching, you can implement a custom `__hash__` instead of using `cache_hash=True`.

**Comment by gabbard** [comment]
@pganssle : It has been a long time since I've touched this code, so I could be mistaken, but I believe your solution should work fine.
