### ISSUE TITLE
evolve method on attr-generated classes.

### ISSUE THREAD

**Issue by maffoo** [python-attrs/attrs#525]
I think it could be useful to optionally add an `evolve` method on classes annotated with `attr.s`. This method would basically be equivalent to:
```python
def evolve(self, **changes):
    return attr.evolve(self, **changes)
```
except that since it is being generated for a specific class the signature of the `evolve` method could match that of the class constructor so that for example you could get type-checking of the names passed to `evolve`. Does this seem reasonable/desirable?

**Comment by Tinche** [comment]
The problem in this case is that you can't have an `evolve` attribute on your class (or a custom evolve method of your own implementation). We could add logic to avoid creating this method in certain cases but that just introduces extra magic, and it's not worth it if you can just import evolve from attrs.

**Comment by maffoo** [comment]
I would imagine that this method only gets added if you request it, via a new argument to `attr.s`, something like:
```python
@attr.s(evolve_instance=True)
class SomeClass:
    a: int = attr.ib()
    ...
```
`evolve_instance` would default to `False`, but if you explicitly set it to `True` then we would create an `evolve` method on the instance.

**Comment by wsanchez** [comment]
I agree that this would have to be opted into, if implemented.

And I'd make it a `str`, not `bool`, so you can choose the name of the method. (`datetime.datetime`, for example, calls a similar method `replace`.)

**Comment by hynek** [comment]
To be clear, the entire point of this exercise is to have correct type hints on the evolve method? Would that need changes to the mypy plugin? Because if yes, we could just as well try to make it evolve-aware?

**Comment by wsanchez** [comment]
I'm not sure that's the entire point.  It does make sense to have such an API on the object being `evolve`-ified, rather than clients importing a thing from `attrs`.  It's only the two lines that @maffoo shows above, but those two lines look a lot like boilerplate.  :-)

That a class uses `attrs` at all might be be seen as an implementation detail by a developer, but if your clients need to use use API from `attrs` to work with your classes, then your classes have become tightly coupled to `attrs` as a compatibility matter.  Perhaps that ship has sailed?

**Comment by hynek** [comment]
I don't think there's anything left to be done here.
