### ISSUE TITLE
Attribute changed notification hooks

### ISSUE THREAD

**Issue by danieljfarrell** [python-attrs/attrs#622]
I'm interested in extending attrs to provide change notifications. Or at least making my classes generated with attrs emit notifications when an attribute changes.

How would you go about doing this?

I'm wondering if attrs could generate an `'x'_did_change` method/notification hook when synthesizing the attributes. This is similar to [traitlets trait change notifications/observations](https://traitlets.readthedocs.io/en/stable/api.html#callbacks-when-trait-attributes-change) although that's more dynamic as observers can be added and removed at runtime.

```python
import attr
import typing

@attr.s(auto_attribs=True)
class SomeClass:
    a_number: int = 42
    list_of_numbers: typing.List[int] = attr.Factory(list)

    def _a_number_did_change(self, info):
        old = info['old']
        new = info['new']

    def _list_of_numbers_did_change(self, info):
        added = info['added']
        removed = info['removed']
```

**Comment by hynek** [comment]
What you're asking for is attrs to start writing a `__setattr__` for you too. This could happen and allow us to add setter-validation too by adding our own hooks (which people have been asking for forever). 🤔

You should be able to implement it yourself for now: put the hooks into the attribute's meta field and write a `__setattr__` that runs them.

**Comment by altendky** [comment]
If I remember correctly it's a pile (of bad stuff) and maybe I shouldn't share it here... but I wrote up an implementation of this idea for use in my PyQt applications.  It definitely needs to be rewritten.  It went the route of generating `@properties` that implement on-change `pyqtSignal` emission as well as conversion/validation.  The classes processed by this are used to back Qt models in my GUIs.

code: https://github.com/altendky/stlib/blob/fc519e561adddb930c1dc7cdc6a74bd5290d3c95/epyqlib/utils/qt.py#L914
tests: https://github.com/altendky/stlib/blob/fc519e561adddb930c1dc7cdc6a74bd5290d3c95/epyqlib/tests/utils/test_qt.py

Anyways, hopefully this doesn't waste someone else's time.  Figured I'd share something rather than just clicking the subscribe button.

**Comment by gshaikov** [comment]
@danieljfarrell hi Daniel, are you planning to work on it? Otherwise I can pick this up. This feature will be handy in our org.

**Comment by gshaikov** [comment]
@hynek I saw your comment about `__setattr__`, what prompted you to abandon it?
https://github.com/python-attrs/attrs/pull/233#issuecomment-323537478

**Comment by hynek** [comment]
I literally wrote it in the next sentence. :). I didn't want to touch another dunder method but that reason has fallen away since we _do_ touch `__setattr__` now for frozen classes.  If I had the time, I'd put it back.

**Comment by hynek** [comment]
I guess I could imagine an API similar to this:

```python
x = attr.ib(set_hook=validate_if_has_validator)
```

with the usual syntactic sugar for combination using lists.

**Comment by hynek** [comment]
Please have a look at #660.

**Comment by hynek** [comment]
I believe this is fixed.
