### ISSUE TITLE
Request: one line to explain what `s` and `ib` stand for in the API docs

### ISSUE THREAD

**Issue by codekiln** [python-attrs/attrs#726]
To better honor the spirit of [PEP 20's _Explicit is better than implicit_](https://www.python.org/dev/peps/pep-0020/) and the library's [_No surprises_ philosophy](https://www.attrs.org/en/stable/overview.html#philosophy), consider adding something like this in or immediately after _the first line_ of the API docs for {[`attr.s`](https://www.attrs.org/en/stable/api.html?highlight=ib#attr.s), [`attr.ib`](https://www.attrs.org/en/stable/api.html?highlight=ib#attr.ib)}: "Note: {`.s`, `.ib`} is not an abbreviation; {`attr.s`, `attr.ib`} is meant to look like {`attrs`, `attrib`}. See the [_On the `attr.s` and `attr.ib` Names_ section in the Overview for more information](https://www.attrs.org/en/stable/overview.html#on-the-attr-s-and-attr-ib-names)."

I'm probably not the only one to see the `Note` included in those API doc entries (way beneath the changelog) and wonder why the library authors chose to leave abbreviation expansion as an exercise left to potential library adopters, having not seen the Overview note.

**Comment by cipri-tom** [comment]
I agree, the first time I looked at attrs it was quite uncomfortable -- I kept wondering "what's an `s` and an `ib` ?" :D

**Comment by hynek** [comment]
Well, there's https://www.attrs.org/en/stable/overview.html#on-the-attr-s-and-attr-ib-names and 
![Screenshot 2020-12-03 at 06 20 34](https://user-images.githubusercontent.com/41240/100967558-c765ba80-352f-11eb-85bf-4fcf589fad2d.png) on the homepage mentions that it's in there?

I could elaborate a bit more, that the original reason for those short terms is basically, that before type annotation, you had to write it out every, single, time. Since that's not the case anymore, [we're moving away from them as the main API](https://www.attrs.org/en/stable/api.html#provisional-apis).

**Comment by cipri-tom** [comment]
hah, I had missed that bullet point 😅. I shall read docs more in-depth before starting to use something.

Well, since they are superseded in the new API, I guess it's OK to leave as it is for now, there's enough explanation for newcomers.

**Comment by codekiln** [comment]
The request above is to make a hyperlink to that explanation in the API docs.

**Comment by hynek** [comment]
I hope all concerns have been adequately fixed by #871.
