### ISSUE TITLE
`twisted.logger.Logger` as class variable is incorrectly typed as `object` in method definition

### ISSUE THREAD

**Issue by wsanchez** [python-attrs/attrs#823]
When I use a `twisted.logger.Logger` object as a class variable, Mypy thinks that it's type is `object` when in a method scope:

```python
"""
To test, run:

python3.8 -m venv /tmp/e
/tmp/e/bin/pip install attrs twisted mypy
/tmp/e/bin/mypy test.py


Mypy output:

test.py:32: note: Revealed type is "test.Foo"
test.py:35: note: Revealed type is "twisted.logger._logger.Logger"
test.py:38: note: Revealed type is "test.Foo"
test.py:39: note: Revealed type is "builtins.object"
test.py:43: note: Revealed type is "builtins.object"
"""

from typing import ClassVar

from attr import attrs

from twisted.logger import Logger


class Foo:
    pass


@attrs(auto_attribs=True)
class Bar:
    foo: ClassVar[Foo] = Foo()
    reveal_type(foo)  # Revealed type is "test.Foo"

    log: ClassVar[Logger] = Logger()
    reveal_type(log)  # Revealed type is "twisted.logger._logger.Logger"

    def blah(self) -> None:
        reveal_type(self.foo)  # Revealed type is "test.Foo"
        reveal_type(self.log)  # Revealed type is "builtins.object"  <- ?!?!?!!
        return None


reveal_type(Bar.log)  # Revealed type is "builtins.object"  <- ?!?!?!!
```

Here is [the definition (with type hints) for `Logger.__get__`](https://github.com/twisted/twisted/blob/trunk/src/twisted/logger/_logger.py#L71):

```python
    def __get__(self, instance: object, owner: Optional[type] = None) -> "Logger":
```

**Comment by hynek** [comment]
How likely is this out bug and how likely is this mypy? If there’s descriptors involved I’d guess on MyPy? 🤔

**Comment by euresti** [comment]
So this doesn't appear to be attrs related.  If you take out attrs you have the same issue.  Here's a much smaller example.

```

from twisted.logger._logger import Logger

x = Logger()
reveal_type(x)

class Foo:
    x: Logger
    y: int

reveal_type(Foo().x)
reveal_type(Foo().y)
```

No Classvars and no attrs involved.  Oh now I see the problem and you mentioned it.  The descriptor says it return an `object`
so that's the actual problem.  (i.e. This is a Twisted stubs issue) 

However it's not exactly correct to have the descriptor return `Logger` because of inheritance.  And I tried adding [Self Types](https://mypy.readthedocs.io/en/latest/generics.html#generic-methods-and-generic-self) but that didn't seem to work.  Perhaps the solution is to put the descriptor under `if TYPE_CHECKING:` and call it a day.

Anyway as this is not an attrs problem I'm closing this bug.  I would possibly reopen this over in Twisted, though I know their stubs are in quite a bit of flux.

**Comment by wsanchez** [comment]
@euresti Thanks for the help here and sorry about the lack of actually confirming `attrs` being in play.

Self types did seem to work for me, FWIW:

https://mypy-play.net/?mypy=latest&python=3.9&gist=3cf60b226d67003080f781f121587014

**Comment by euresti** [comment]
Oh cool. They seem to work for me today, weird.
