### ISSUE TITLE
Inheriting with `attr.mutable` or `attr.define` classes raises `TypeError`.

### ISSUE THREAD

**Issue by nxtlo** [python-attrs/attrs#880]
Example code.
```py
import attr

@attr.define(weakref_slot=False)
class User:
    id: int = attr.field()
    name: str = attr.field()

@attr.define(weakref_slot=False)
class Member:
    id: int = attr.field()
    name: str = attr.field()
    
@attr.define(weakref_slot=False)
class UserImpl(User, Member):
    id: int = attr.field()
    name: str = attr.field()

u = UserImpl(id=1, name="name")
print(u)
```

The example above raises this exception `TypeError: multiple bases have instance lay-out conflict` which only occurs while inheriting from multiple classes decorated with either `attr.mutable` <-> `attr.define`. `attr.s` works fine. Is there a reason why this is happening?

**Comment by hynek** [comment]
The reason is that define/mutable have `slots=True` by default and that is problematic with multiple inheritance in Python in general. See  https://docs.python.org/3/reference/datamodel.html#notes-on-using-slots (second to last point) and/or https://www.attrs.org/en/stable/glossary.html#term-slotted-classes

**Comment by nxtlo** [comment]
I see, thanks.
