### ISSUE TITLE
Missing requirement for `attr` 

### ISSUE THREAD

**Issue by CatChenal** [python-attrs/attrs#923]
I discovered that the library `attr` is not installed automatically when I attempted to launch [markdown-it-py repo](https://github.com/executablebooks/markdown-it-py) on gitpod (i.e. on a __fresh environment__). This repo uses the `attrs` library.

### Problem: missing requirement for `attr` in [setyp.py](https://github.com/python-attrs/attrs/blob/main/setup.py):
```
[48] INSTALL_REQUIRES = []
```

**Comment by CatChenal** [comment]
Issue cross-posted: [markdown-it-py issue #201](https://github.com/executablebooks/markdown-it-py/issues/201)

**Comment by hynek** [comment]
The PyPI name and the importable package name are two independent things, although often identical. 

Currently, if you install`attrs` From PyPI you get two importable packages: `attr` (since day 1) and `attrs` (as of 21.3).

If you’re interested in the why and the historical background, check out  <https://hynek.me/articles/import-attrs/>.
