### ISSUE TITLE
Infinite Recursion in repr with bi-directional relationships

### ISSUE THREAD

**Issue by dcbaker** [python-attrs/attrs#95]
Take a fairly trivial example (which has obviously been simplified to the point of absurdity):

``` python
import attr

@attr.s
class Test():
    attr = attr.ib(default=None)

test = Test()
other = Test()
test.attr = other
other.attr = test

print(repr(test))
```

This will result in infinite recursion. This can be worked around by setting `repr=False` in the attr.s decorator.

I've sat on this bug for a week trying to come up with a good solution, and I can't think of anything good. I'm starting to think the best solution is to add a warning to the documentation of this behavior and calling it good.

**Comment by rdpate** [comment]
How do lists handle this?  (Where does list.\_\_repr\_\_ store state?)

```
Python 3.5.2 (default, Jul  2 2016, 07:15:59) 
[GCC 4.2.1 Compatible FreeBSD Clang 3.4.1 (tags/RELEASE_34/dot1-final 208032)] on freebsd10
Type "help", "copyright", "credits" or "license" for more information.
>>> import attr
>>> @attr.s
... class A:
...     a = attr.ib(default=None)
... 
>>> L = []
>>> L.append([A(L)])
>>> L
[[A(a=[...])]]
```

**Comment by dcbaker** [comment]
This seems relavent:
https://github.com/python/cpython/blob/8285672c6e174601589cc55cbe71d301488d3767/Objects/listobject.c#L369

It looks like they test the call for the recursion error and somewhere below that they replace it with ... .

**Comment by rdpate** [comment]
I don't think attrs could easily use the same strategy without handling all RecursionErrors.  I think it would be better to do what you first suggested: note in the docs, but don't handle it.

If someone needs to handle it for a specific class, they can replace the generated \_\_repr\_\_, and can probably do a better job.

**Comment by dcbaker** [comment]
Yeah, that's kinda what I though too.

**Comment by perkinslr** [comment]
Usually I solve this kinda thing by using a `set` to track which objects are currently being `repr`ed, if `self` is already in the set, return `...` instead of the usual value, when done, remove `self` from the set.  The only tricky part is figuring out how best to pass the set from one object to the next, since `__repr__` doesn't take an argument.  Probably would need a helper method that `__repr__` calls, that can explicitly pass a set.

**Comment by hynek** [comment]
Yes I thought about something like that too.

**Comment by rdpate** [comment]
The problem is you have no place to store that state (the set), so it ends up being mutable global state.  I suspect the problems caused by that will be worse than "<unprintable ... object>" and RuntimeError("maximum recursion depth exceeded").  At least for the default behavior, and remembering the vast majority of uses will not be cycles.

(List cheats by not storing state and handling the exception instead.  However, list does it slightly differently than we could in pure Python, and it would be complicated to emulate that.  AFAICT, please correct.)

**Comment by dcbaker** [comment]
It wouldn't have to be mutable global state, attrs could generate it's own \_\_attrs_repr\_\_ (or similar) that takes an argument of a set or list (I don't think it would really matter since I think you'd need to call \_\_contains\_\_ at each step), you'd just call down the chain passing the instance until \_\_contains\_\_ came back true, then you'd just print "..."; and the attrs generated \_\_repr\_\_ would call \_\_attrs_repr\_\_. Unless I've completely overlooked something?

Of course, that would require adding another method and some overhead to the \_\_repr\_\_ method.

**Comment by rdpate** [comment]
You can't ensure \_\_attrs\_repr\_\_ exists on all attributes of a class, in order to pass that parameter.  Here, A's repr calls list's repr which calls A's repr, but the cycle could be arbitrarily deeper or longer.

```
@attr.s
class A:
  x = attr.ib()
a = A([])
a.x.append(a)
```

**Comment by dcbaker** [comment]
The bulitins at least do the right thing in that case (set, list, dict).  Your example would resolve to 'A(x=[A(x=[...])])', for example (at least on python 3.5, maybe this doesn't work on python 2?).

What about this? (obviously this is incomplete, it only handles the bits relevant to the stack)
```python
def __attr_repr__(self, stack=None)
    stack = stack or []

    if self in stack:
        return '...'

    stack.append(self)

    try:
        r = child.__attr_repr__(stack)
    except AttributeError:
        try:
            r = child.__repr__()
        except RecurssionError:
            r = '...'
    # XXX: might need to handle a RecursionError here too, since one could
    # create a chain that big? If they did the assert below would fail

    assert stack[-1] is self
    del stack[-1]

    return r
```

This only place I could see this doing something less than ideal would be for classes that implement their own \_\_repr\_\_ method that does recursion, but in that case it should be replaced with "..."; it wouldn't be perfect but better than raising an exception like it does now, and that wouldn't be a problem for attr to solve anyway.

**Comment by rdpate** [comment]
[RecursionError](https://docs.python.org/3/library/exceptions.html#RecursionError) didn't exist prior to Python 3.5 (I made the same mistake in an edited earlier comment here); a RuntimeError was used previously. Even with the special exception class in 3.5, I'm leery of hiding a true error as a "..." string (when cycles are involved, a recursion limit exception could easily be unintentional), though there is no need for the stack at all if that's what you want.

> it wouldn't be perfect but better than raising an exception like it does now

Would it be better than raising an exception? I think the exception is better in general for this case, compared to trying to handle an uncommon or rare case in an unsurprising, on-by-default, one-size-fits-all hack.  Your code above still doesn't handle:

```
@attr.s
class A:
    x = attr.ib()
a = A([])
a.x.append(a)
```

Because list doesn't have the special repr method and the exception is caught "inside" the call chain.  For example, it's equivalent (AFAICT, please correct) to:

```
>>> def f():
...     try:
...         return "x" + f()
...     except RecursionError:
...         return "-"
... 
>>> print(f())
xxx[...]xxx-
```
Rather than "x-" or "-" for the last line, which is what we desire here. (Desire "A(...)" not "A(A(A([...]A(...)[...])))".)

**Comment by glyph** [comment]
`threading.local` (sorry/not sorry)
